/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_helloworld_Main */

#ifndef _Included_main_java_helloworld_Main
#define _Included_main_java_helloworld_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_java_helloworld_Main
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_helloworld_Main_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
