/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_helloworld_UserDataController */

#ifndef _Included_main_java_helloworld_UserDataController
#define _Included_main_java_helloworld_UserDataController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_java_helloworld_UserDataController
 * Method:    createUser
 * Signature: (Ljava/lang/String;D)Lmain/java/helloworld/UserData;
 */
JNIEXPORT jobject JNICALL Java_main_java_helloworld_UserDataController_createUser
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     main_java_helloworld_UserDataController
 * Method:    printUser
 * Signature: (Lmain/java/helloworld/UserData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_java_helloworld_UserDataController_printUser
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
