/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_helloworld_ExchangeData */

#ifndef _Included_main_java_helloworld_ExchangeData
#define _Included_main_java_helloworld_ExchangeData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_java_helloworld_ExchangeData
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_main_java_helloworld_ExchangeData_sumIntegers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     main_java_helloworld_ExchangeData
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_java_helloworld_ExchangeData_sayHelloToMe
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
